// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Model.Configuration;

#nullable disable

namespace Sample.Model.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Entity.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Number")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("NUMBER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TEST_ENTITIES");
                });

            modelBuilder.Entity("Model.Entity.TestManyToOne", b =>
                {
                    b.Property<int>("TEST_ID")
                        .HasColumnType("int");

                    b.Property<int?>("TEST_SECOND_ID")
                        .HasColumnType("int");

                    b.HasKey("TEST_ID");

                    b.HasIndex("TEST_SECOND_ID");

                    b.ToTable("TEST_MTOS");
                });

            modelBuilder.Entity("Model.Entity.TestManyToOne", b =>
                {
                    b.HasOne("Model.Entity.TestEntity", "TestEntity")
                        .WithMany("TestManyToOnes")
                        .HasForeignKey("TEST_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.TestEntity", "TestSecondEntity")
                        .WithMany("TestSecondManyToOnes")
                        .HasForeignKey("TEST_SECOND_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TestEntity");

                    b.Navigation("TestSecondEntity");
                });

            modelBuilder.Entity("Model.Entity.TestEntity", b =>
                {
                    b.Navigation("TestManyToOnes");

                    b.Navigation("TestSecondManyToOnes");
                });
#pragma warning restore 612, 618
        }
    }
}
