// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Model.Configuration;

#nullable disable

namespace Sample.Model.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sample.Model.Entity.AdvancedEmailVerificationCode", b =>
                {
                    b.Property<Guid>("CODE_ID")
                        .HasColumnType("char(36)");

                    b.HasKey("CODE_ID");

                    b.ToTable("ADVANCED_EMAIL_CODES", (string)null);
                });

            modelBuilder.Entity("Sample.Model.Entity.Code", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("DISCRIMINATOR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TYPE");

                    b.Property<int?>("USER_ID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("USER_ID");

                    b.ToTable("USER_HAS_CODES", (string)null);

                    b.HasDiscriminator<string>("DISCRIMINATOR").HasValue("Code");
                });

            modelBuilder.Entity("Sample.Model.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("BALANCE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Sample.Model.Entity.EmailVerificationCode", b =>
                {
                    b.HasBaseType("Sample.Model.Entity.Code");

                    b.HasDiscriminator().HasValue("EMAIL");
                });

            modelBuilder.Entity("Sample.Model.Entity.AdvancedEmailVerificationCode", b =>
                {
                    b.HasOne("Sample.Model.Entity.EmailVerificationCode", "Code")
                        .WithMany()
                        .HasForeignKey("CODE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EFCAT.Model.Data.Image", "Image", b1 =>
                        {
                            b1.Property<Guid>("AdvancedEmailVerificationCodeCODE_ID")
                                .HasColumnType("char(36)");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("longblob")
                                .HasColumnName("IMAGE_CONTENT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("varchar(32)")
                                .HasColumnName("IMAGE_TYPE");

                            b1.HasKey("AdvancedEmailVerificationCodeCODE_ID");

                            b1.ToTable("ADVANCED_EMAIL_CODES");

                            b1.WithOwner()
                                .HasForeignKey("AdvancedEmailVerificationCodeCODE_ID");
                        });

                    b.Navigation("Code");

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("Sample.Model.Entity.Code", b =>
                {
                    b.HasOne("Sample.Model.Entity.User", "User")
                        .WithMany("Codes")
                        .HasForeignKey("USER_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("EFCAT.Model.Data.Image", "QR", b1 =>
                        {
                            b1.Property<Guid>("CodeId")
                                .HasColumnType("char(36)");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("longblob")
                                .HasColumnName("QR_CONTENT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("varchar(32)")
                                .HasColumnName("QR_TYPE");

                            b1.HasKey("CodeId");

                            b1.ToTable("USER_HAS_CODES");

                            b1.WithOwner()
                                .HasForeignKey("CodeId");
                        });

                    b.Navigation("QR")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sample.Model.Entity.User", b =>
                {
                    b.OwnsOne("EFCAT.Model.Data.Image", "Image", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("longblob")
                                .HasColumnName("IMAGE_CONTENT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("varchar(32)")
                                .HasColumnName("IMAGE_TYPE");

                            b1.HasKey("UserId");

                            b1.ToTable("USERS");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Sample.Model.Entity.User", b =>
                {
                    b.Navigation("Codes");
                });
#pragma warning restore 612, 618
        }
    }
}
